### PR TITLE
scalapack v2.1.0

### PR DESCRIPTION
**Pull request by traversaro**
Based on https://github.com/conda-forge/scalapack-feedstock/pull/17 .
Patch `0001-mpi3.patch` removed as it is already contained in v2.1.0 via https://github.com/Reference-ScaLAPACK/scalapack/pull/10 .
CMake patch removed as superseded by https://github.com/Reference-ScaLAPACK/scalapack/pull/14 .
CMake pinned to 3.20 to workaround `-fortranlibs` problem (see https://github.com/conda-forge/scalapack-feedstock/pull/21#issuecomment-892033610).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The build is failing with error:
~~~
2021-08-03T17:06:39.3842449Z x86_64-conda-linux-gnu-cc: error: unrecognized command line option '-fortranlibs'
2021-08-03T17:06:39.3858059Z make[2]: *** [REDIST/TESTING/CMakeFiles/xsgemr.dir/build.make:100: scalapack/REDIST/TESTING/xsgemr] Error 1
~~~
It seems that CMake itself is inserting the `-fortranlibs` flags when finding LAPACK:
~~~
2021-08-03T17:03:11.9278277Z -- Found LAPACK: $PREFIX/lib/liblapack.so;$PREFIX/lib/libblas.so;-fortranlibs  
2021-08-03T17:03:11.9287440Z -- BLAS library: $PREFIX/lib/libblas.so
2021-08-03T17:03:11.9288575Z -- LAPACK library: $PREFIX/lib/liblapack.so;$PREFIX/lib/libblas.so;-fortranlibs
~~~
This seems related to a recent CMake change: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6089 .

**Comment by traversaro** [comment]
> 
> 
> The build is failing with error:
> 
> ```
> 2021-08-03T17:06:39.3842449Z x86_64-conda-linux-gnu-cc: error: unrecognized command line option '-fortranlibs'
> 2021-08-03T17:06:39.3858059Z make[2]: *** [REDIST/TESTING/CMakeFiles/xsgemr.dir/build.make:100: scalapack/REDIST/TESTING/xsgemr] Error 1
> ```
> 
> It seems that CMake itself is inserting the `-fortranlibs` flags when finding LAPACK:
> 
> ```
> 2021-08-03T17:03:11.9278277Z -- Found LAPACK: $PREFIX/lib/liblapack.so;$PREFIX/lib/libblas.so;-fortranlibs  
> 2021-08-03T17:03:11.9287440Z -- BLAS library: $PREFIX/lib/libblas.so
> 2021-08-03T17:03:11.9288575Z -- LAPACK library: $PREFIX/lib/liblapack.so;$PREFIX/lib/libblas.so;-fortranlibs
> ```
> 
> This seems related to a recent CMake change: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6089 .

Indeed, temporarly pinning CMake to 3.20 seems to solve the issue. @conda-forge/scalapack the PR is ready for review.

**Comment by dalcinl** [comment]
LGTM. Should I merge?

**Comment by traversaro** [comment]
> 
> 
> LGTM. Should I merge?

Ok for me. I will open an issue on CMake issue tracker for the `fortranlibs` problem, but I guess we do not need to wait on that to merge the PR.

**Comment by isuruf** [comment]
`fortranlibs` problem was an issue with our compiler package. Fixed now

**Comment by traversaro** [comment]
> 
> 
> `fortranlibs` problem was an issue with our compiler package. Fixed now

Great, thanks!

**Pull request merged**
