### PR TITLE
[draft] Arm test

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I'm giving up .. does anyone have an idea why the linking step fails?
```
[ 63%] Linking Fortran shared library lib/libscalapack.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture arm64:
  "_MPI_Abort", referenced from:
      _BI_BlacsAbort in BI_BlacsAbort.c.o
  "_MPI_Allreduce", referenced from:
      _igsum2d_ in igsum2d_.c.o
      _sgsum2d_ in sgsum2d_.c.o
      _dgsum2d_ in dgsum2d_.c.o
      _cgsum2d_ in cgsum2d_.c.o
      _zgsum2d_ in zgsum2d_.c.o
      _igamx2d_ in igamx2d_.c.o
      _sgamx2d_ in sgamx2d_.c.o
      ...
  "_MPI_Barrier", referenced from:
      _blacs_barrier_ in blacs_barr_.c.o
      _Cblacs_barrier in blacs_barr_-C.c.o
  "_MPI_Bcast", referenced from:
      _igebs2d_ in igebs2d_.c.o
      _sgebs2d_ in sgebs2d_.c.o
      _dgebs2d_ in dgebs2d_.c.o
      _cgebs2d_ in cgebs2d_.c.o
      _zgebs2d_ in zgebs2d_.c.o
      _igebr2d_ in igebr2d_.c.o
      _sgebr2d_ in sgebr2d_.c.o
      ...
  "_MPI_Comm_create", referenced from:
      _Cblacs_gridmap in blacs_map_-C.c.o
      _BI_TransUserComm in BI_TransUserComm.c.o
  "_MPI_Comm_dup", referenced from:
      _blacs_gridmap_ in blacs_map_.c.o
      _Cblacs_gridmap in blacs_map_-C.c.o
  "_MPI_Comm_free", referenced from:
      _blacs_gridexit_ in blacs_grid_.c.o
      _Cblacs_gridexit in blacs_grid_-C.c.o
  "_MPI_Comm_get_attr", referenced from:
```

/cc @conda-forge/scalapack @jschueller

**Comment by jschueller** [comment]
I think I was stuck on this too

**Comment by traversaro** [comment]
@Tobias-Fischer what point in the history do you think it is the best one to start from on this PR?

**Comment by Tobias-Fischer** [comment]
I think the last commit should be alright - my best guess is that https://github.com/Tobias-Fischer/scalapack-feedstock/blob/3bb433e3588aab571033e81b77c489ee910bd427/recipe/build.sh#L16-L19 needs updating.

Thanks for tackling this!

**Comment by traversaro** [comment]
Thanks! Probably I will look first in updating this to 2.2.0, and then I look into this.

**Comment by Tobias-Fischer** [comment]
See #31 instead

**Pull request closed without merging**
