### PR TITLE
Update openblas pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by pstjohn** [comment]
conda-forge/mumps-feedstock#20
conda-forge/ipopt-feedstock#12

**Comment by jschueller** [comment]
ci passed

**Comment by jschueller** [comment]
@pstjohn could you merge this ?

**Comment by pstjohn** [comment]
I can’t, I don’t maintain this feedstock. Just tagging the dependency tree for the upstream repos. @minrk?

**Comment by jschueller** [comment]
@conda-forge/core could someone merge this ?

**Pull request merged**
